import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { toast } from 'react-toastify';
import { confirmEmail } from '../../api';

export default function ConfirmEmail() {
  const [confirming, setConfirming] = useState(true);
  const navigate = useNavigate();
  const { id } = useParams();

  //use id generated by mongo
  useEffect(() => {
    const confirm = async () => {
      try {
        if (!id) {
          toast.error('No ID provided for email confirmation');
          navigate('/login');
          return;
        }

        const response = await confirmEmail(id);

        setConfirming(false);
        if (response.data.msg === 'Could not find you!') {
          toast.error(response.data.msg);
        } else {
          toast.success(response.data.msg);
        }
      } catch (error) {
        console.log(error);
        navigate('/login');
      }
    };

    confirm();
  }, [id, navigate]);

  return (
    <div className='confirm text-center mt-3'>
      {confirming ? (
        <h2>Veryfing email...</h2>
      ) : (
        <Link to='/profile' className='btn btn-warning'>
          Go to your profile
        </Link>
      )}
    </div>
  );
}
