import React, {Component} from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import { confirmEmail } from '../api';

export default class Confirm extends Component {
  state = {
    confirming: true
  }

  //use id generated by mongo 
  componentDidMount = async () => {
    
    const {id} = this.props.match.params;
    try {
        const response = await confirmEmail(id);
        this.setState({confirming: false});
        toast.success(data.msg);
    } catch (error) {
        console.log(error);
    }
  }

  render = () =>
    <div className='confirm'>
      {this.state.confirming
        ? <Spinner size='8x' spinning={'spinning'} /> 
        : <Link to='/'>
            <Spinner size='8x' spinning={''} /> 
          </Link>
      }
    </div>
}